### ISSUE TITLE
Email address with apostrophe is treated as invalid

### ISSUE THREAD

**Issue by diksta** [hmrc/emailaddress#11]
One of my colleagues has a digital email address with an apostrophe in it:-
    EmailAddress.isValid("john.o'neil@digital.hmrc.gov.uk”) returns false
Is there any reason that https://github.com/hmrc/emailaddress/blob/master/src/main/scala/uk/gov/hmrc/emailaddress/EmailAddress.scala doesn’t allow it. Does this regex fully comply with the RFC for email address? Although most sites only allow basic email address’s (like creating an Oracle account) even gmail returns a “Please only use letters (a-z), numbers and periods”. GDS’s blog registration does allow the above email though.

**Comment by diksta** [comment]
Ultimately our email validation has to reflect what our email integration can accept. At the moment, that's MailGun.

Having said that, I think the email you specified is valid in MailGun and therefore should be valid in the EmailAddress RegEx.

You can check if an email is valid in MailGun here: http://mailgun.github.io/validator-demo/

**Comment by grahampaulcook** [comment]
Yes that link returns "Address is valid."

**Comment by diksta** [comment]
Then a pull request to allow these type of emails makes sense.

The intention is not to confirm if an email is definitely valid, just to confirm if it's obviously not :-)

**Comment by grahampaulcook** [comment]
Created https://github.com/hmrc/emailaddress/pull/12

**Comment by howyp** [comment]
Fixed in 2d51e177106a2aa584d478ea55825a641626964f
