### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by rgomezcasas** [hmrc/emailaddress#17]
Hey,

Could you provide support for Scala 2.12? If you can provide me some help I can do the change :)

Thanks!

**Comment by tmacedo** [comment]
While official 2.12 builds are not available, I'm building it myself and publishing on bintray: https://bintray.com/tmacedo/maven/emailaddress

It points to this repo and has the right license so I think it should be fine but let me know if something needs changing.
