### ISSUE TITLE
Remove dependency on play-json

### ISSUE THREAD

**Issue by mgladdish** [hmrc/emailaddress#3]
I'm using this library outside play, and I would really like not to have to include the `play-json` library. Firstly because I don't need a json representation of an email address, secondly because of the large set of dependencies `play-json` pulls in:
- `com.typesafe.play : play-iteratees_2.10`
- `com.typesafe.play : play-functional_2.10`
- `com.typesafe.play : play-datacommons_2.10`
- `joda-time : joda-time`
- `org.joda : joda-convert`
- `com.fasterxml.jackson.core : jackson-annotations`
- `com.fasterxml.jackson.core : jackson-core`
- `com.fasterxml.jackson.core : jackson-databind`

Requiring this lot is a bit of a hidden gotcha for a micro library.

**Comment by duncancrawford** [comment]
@mgladdish please feel free to submit a PR. Currently play-json is added for the Reads[EmailAddress] & Writes[EmailAddress] impls, re. https://github.com/hmrc/emailaddress/blob/master/src/main/scala/uk/gov/hmrc/emailaddress/EmailAddress.scala#L25

**Comment by howyp** [comment]
It's a provided dependency, so it shouldn't be required unless you want to use the formats. 

Having said that, I suspect there may be an issue with the object initialisation that stops the library from working without play. I'll try and look at this later - do you experience that?

**Comment by mgladdish** [comment]
Yes, that’s the issue; I’ve already tried using it without the optional dependency. Even though the format member is lazy, the class loader still attempts to reference all, er, references.

**Comment by howyp** [comment]
I suspect that it's the type of the lazy val at https://github.com/hmrc/emailaddress/blob/master/src/main/scala/uk/gov/hmrc/emailaddress/EmailAddress.scala#L22 that's causing the classloader to try to load Play classes. I can't look at this now but will try to come up with a fix later today or tomorrow.
