### ISSUE TITLE
Dependency on Play

### ISSUE THREAD

**Issue by programmatix** [hmrc/emailaddress#7]
Thanks for creating this library.  I'm trying to use it and getting this error:

[error] missing or invalid dependency detected while loading class file 'EmailAddress.class'.
[error] Could not access term play in package <root>,

Looks like there is a dependency on the Play project?  I'm reluctant to pull in a big framework for a microlib, and it looks like the dependency is there for a very small part of the lib.  Any chance it could be factored out, maybe a separate emailaddress-play lib?

**Comment by howyp** [comment]
Hi Graham, thanks for reporting. 

You shouldn't get this error in the latest versions, the play dependency should be able to be missing as long as you don't use `PlayJsonFormats`. 

Could you confirm that this is occurring with version 0.4.0 please?

**Comment by programmatix** [comment]
Ah, my bad, it does indeed work fine with 0.4.0.  I couldn't immediately see from the project page what the latest version was, so had a quick look on mavenrepository and decided the latest version was 0.2.0, missing that you have your own resolver.

**Comment by howyp** [comment]
No worries - glad it works :-)

We have a bintray button at the top of our projects that shows the latest version number. I'm guess that wasn't obvious enough - anything else you think we could do?

**Comment by programmatix** [comment]
Yeah it's pretty clear, now I know it's there.  Many libraries put the latest version in this bit:

libraryDependencies += "uk.gov.hmrc" %% "emailaddress" % "x.x.x"

so I guess I'm hardcoded to look there first, and then try maven next.  It's not a biggy though, chalk it up to user error.
